### ISSUE TITLE
1.1.0 won't build (TS problems)

### ISSUE THREAD

**Issue by chasm** [staylor/react-helmet-async#140]
Suddenly getting this:

```
node_modules/react-helmet-async/index.d.ts:1:43 - error TS2307: Cannot find module './Provider' or its corresponding type declarations.

1 export { default as HelmetProvider } from "./Provider";
                                            ~~~~~~~~~~~~

src/routes/some-file/index.tsx:24:10 - error TS2786: 'Helmet' cannot be used as a JSX component.
  Its instance type 'Helmet' is not a valid JSX element.
    Type 'Helmet' is missing the following properties from type 'ElementClass': context, setState, forceUpdate, props, and 2 more.

24         <Helmet>
            ~~~~~~
```

1.0.9 builds just fine.

**Comment by cabello** [comment]
I am facing the same issue after upgrading from 1.0.9 to 1.3.0:

```typescript
'Helmet' cannot be used as a JSX component.
  Its instance type 'Helmet' is not a valid JSX element.  TS2786

    45 |   return (
    46 |     <MainContainer>
  > 47 |       <Helmet>
       |        ^
    48 |         <title>
    49 |           {intl.formatMessage({
```

My `yarn.lock`:

```
react-helmet-async@^1.0.7, react-helmet-async@^1.3.0:
  version "1.3.0"
  resolved "https://registry.yarnpkg.com/react-helmet-async/-/react-helmet-async-1.3.0.tgz#7bd5bf8c5c69ea9f02f6083f14ce33ef545c222e"
  integrity sha512-9jZ57/dAn9t3q6hneQS0wukqC2ENOBgMNVEhb/ZG9ZSxUetzVIw4iAmEU38IaVg3QGYauQPhSeUTuIUtFglWpg==
  dependencies:
    "@babel/runtime" "^7.12.5"
    invariant "^2.2.4"
    prop-types "^15.7.2"
    react-fast-compare "^3.2.0"
    shallowequal "^1.1.0"
```

1.0.7 comes from storybook 6.4.9 but should be fine as both are resolving to 1.3.0.

Has this regressed or can I do something with my app configuration to fix it?

Thank you for this awesome library 💜

**Comment by arleyGuoLei** [comment]
1.3.0 +1

**Comment by arleyGuoLei** [comment]
try to ugprade @types/react and @types/react-dom with latest versions
