### ISSUE TITLE
Incorrect type for HelmetProvider in index.d.ts

### ISSUE THREAD

**Issue by michalczaplinski** [staylor/react-helmet-async#90]
```
../../node_modules/react-helmet-async/index.d.ts:84:24 - error TS2662: 

Cannot find name 'canUseDOM'. Did you mean the static member 'HelmetProvider.canUseDOM'?

84     static canUseDOM = canUseDOM;
                          ~~~~~~~~~
```

**Comment by le0nik** [comment]
I have 3 type-related errors after upgrading to 1.0.5.
1.0.4 works correctly.

```
node_modules/react-helmet-async/index.d.ts:77:4 - error TS1036: Statements are not allowed in ambient contexts.

77   };
      ~

node_modules/react-helmet-async/index.d.ts:84:24 - error TS1039: Initializers are not allowed in ambient contexts.

84     static canUseDOM = canUseDOM;
                          ~~~~~~~~~

node_modules/react-helmet-async/index.d.ts:84:24 - error TS2662: Cannot find name 'canUseDOM'. Did you mean the static member 'HelmetProvider.canUseDOM'?

84     static canUseDOM = canUseDOM;
                          ~~~~~~~~~


Found 3 errors.

```
